export const MONITORED_KEYWORDS = [
  "rose toy",
  "rose sex toy",
  "tongue licking vibrator",
  "clitoral suction vibrator",
  "sexual wellness vibrator",
  "tongue toy for women",
  "tongue vibrator",
  "rose adult toy",
  "sucking vibrator",
  "vibrator rose",
  "tongue sex toy",
  "sex rose",
  "rose sex toys",
  "adult toy rose",
  "rose sex",
  "tongue vibrator for women",
  "tongue licking toy for women",
  "rose tongue vibrator",
  "rose tongue toy",
  "licking vibrator for women",
  "oral tongue vibrator",
  "rose vibrator for women",
  "clitoral tongue vibrator",
  "tongue massager for women",
  "rose clitoral toy",
] as const;

export const DEFAULT_PRODUCT = {
  name: "TUATIMAR S10",
  asin: "B0GGTPHQZK",
  market: "Amazon US",
  zip: "90001",
  amazonUrl: "https://www.amazon.com/dp/B0GGTPHQZK",
} as const;
